sudo: false
language: scala
scala:
- 2.11.6
env:
  global:
  - secure: DRlCTSr4RzgBhhBexFD3097/TmlFTNFIu47eS8UT7PONS1gctwoM84huaqgURFkPy6QdPvxOmG58uBos3q1s540PhXX4tTU8Y2gJcIZKyF5G3M4Y5rNl+S43ww0+pYGkDcyEWjTWN2V1T4XKPXxPvgldg1gEiOKCxEAuyOyMvmbEPeZMeCswgGF+jolqTIZTiSMUtfQ4c1XIJS/GNKjidpCkfV3nTLZZ2sbhROkfZUIICG5Syerpx/zSgxmgTl1NAf2K7ZFTryaoWt5it0yYhP5i/xkpuDLFFX5SFuHQ6A0uKKZbnqn3ICqODaYFupQ0fkYaKZRa8JJNGkaooZOez/D2rPl51NSjEdjeoouvpbN4Kc68hV9vPULOzq3FpJ9V5llBShlhpIYk4vuUFhsExjhHlXUnH08yurv+0Epn5yJA2Xvq03SZH2WPv4Rx8nkm7OboL8pf+H7Qe8PtLJk5Gc9nzH371q7iB8fkqEaxXpSLvRXB8I1K3SWqxUTwspWuH78/NKy7mqGFDYW0wyfXBImx/R+5DiUxuyl8EU8cdwijO0EEtf7Dz0828gxgAcd+1HCAb9RanhoCtIMwZuIzn6wounW/cgibtTGrMlCWN4ae/vSTxEIhxkmCy9HkllTuuG95XojfINkHmpq9YVqBqOGwUA95XFfoFKM/8a3+zew=
  - secure: hh0UnwLato3MRVJ/Yq5fSnYZb11L+12dIPw51GAP2R2gvZgmStIQDDra/xoklOgzYppi/3gYvSUGdLNy9qBDsX3uzA1LUsCKLgo25FHy5nppFp8um3mswz28GpkK9435PLNpodGTUc5fSGIdN9WMQjFreWf+JggocSVUp0UxeydeSK0qGjfpTwwCgOniLVVoR3DBHNFRtup52zQrdhTxRlTqEZs2UvBLWXM51r3KhqQD1xL07c3EyCYYp3MCp81V0rOYetXagleNZSZlZYnFXXuUTABs9NwyAqvUXimN0vkDA9865Dbd6KYGwsqcsEXq8jNvbxHwxElbBM9oPK+a94Z8Y4WcagTkIN6qByCE3tKLGeZRvKgcURfQM4Rnk1F7wHz4EA2a75El4t0qwqnxKimk9AORa19PrMN5mer8tK0QyPaMo8fpQKPTdyccqsHVh5Il1CHnrc8dRivQ5O+/tkklukmz/1fbjbg7PSxwQt23+dRhQ8L5XDQYxWoIv7ffKkvFAL+Cp1ywAUqIGWRSYBCbG0X5GuU3COM8IfrcGCoNq80Yb4Vi+W4YwMCieBgnIy3aEhr2d3/yMXzBx948+5xdS+gSltNEnplJ6ZTOqjQkSPWm3JLk/hEIdcyvExSu+wvjsEAyoGI4ZiF4DYperE8xkW41TZUM8/boapbZZHE=
jdk:
- oraclejdk8
script:
- sbt clean coverage test
after_success:
- "[[ $TRAVIS_BRANCH == \"master\" ]] && { sbt publish; };"
- sbt coverageReport && sbt coverageAggregate && sbt coveralls
